Wait for Steampipe plugin schemas to become available before running psql
Steampipe is sometimes slow to register schemas for plugins at Postgres
server start.  Or maybe Postgres is slow to import the foreign table
schemas.  Either way, while locally it was always fast enough, in CI it
was often losing the race with our query and causing errors.

Ensure the Steampipe plugin connections (and thus, it seems, schemas)
are in the "ready" state.  This does require that any plugins which are
installed must be set up correctly and able to reach the "ready" state.

diff --git a/steampipe-psql b/steampipe-psql
--- a/steampipe-psql
+++ b/steampipe-psql
@@ -44,6 +44,13 @@ main() {
         ' EXIT
     fi
 
+    # Steampipe is sometimes slow about registering schemas for plugins and if
+    # we try to run a query before they exist it'll fail.
+    while ! steampipe-plugins-ready; do
+        echo "Waiting for Steampipe plugin schemas to be ready…" >&2
+        sleep 1
+    done
+
     echo "Running psql" >&2
 
     # No exec because of our trap above
@@ -59,6 +66,16 @@ print-help-if-requested() {
 
 steampipe-service-available() {
     nc -zw3 "$PGHOST" "$PGPORT" &>/dev/null
+}
+
+steampipe-plugins-ready() {
+    local -a psql=(psql --quiet --no-psqlrc --no-align --tuples-only)
+    local query="
+        select count(*)
+          from steampipe_internal.steampipe_connection
+         where type = 'plugin' and state != 'ready'
+    "
+    [[ "$("${psql[@]}" <<<"$query")" -eq 0 ]]
 }
 
 main "$@"
